backend:
  name: git-gateway
  branch: main

media_folder: "static/assets/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "carousel"
    label: "Carousel"
    folder: "/content/carousel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image1", name: "image1", widget: "image" }
      - { label: "Image2", name: "image2", widget: "image" }
      - { label: "Image3", name: "image3", widget: "image" }
